# Generated by Django 5.0.4 on 2024-04-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_app_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='display_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
